In [4]:
## 上采样测试
import numpy as np

scale_factor = 4
num_upconvs = int(np.log2(scale_factor))
num_upconvs

2

In [5]:
nf = 64
up_channels = None
if up_channels is None:
    up_channels = [nf] * 2 + [nf // 2] * (num_upconvs - 2)

In [6]:
up_channels

[64, 64]

In [7]:
import torch

In [8]:
num_manifolds = 24
levels_start = 23
levels_end = 8
levels = torch.linspace(levels_start, levels_end, num_manifolds-1)

In [9]:
levels

tensor([23.0000, 22.3182, 21.6364, 20.9545, 20.2727, 19.5909, 18.9091, 18.2273,
        17.5455, 16.8636, 16.1818, 15.5000, 14.8182, 14.1364, 13.4545, 12.7727,
        12.0909, 11.4091, 10.7273, 10.0455,  9.3636,  8.6818,  8.0000])

In [10]:
import torch

center = (0, 0, 0)
torch.tensor(center)

tensor([0, 0, 0])

In [16]:
fov = 12
HL = 256
y, x = torch.meshgrid(torch.linspace(-fov/100, fov/100, HL), torch.linspace(-fov/100, fov/100, HL))
y.shape, x.shape

(torch.Size([256, 256]), torch.Size([256, 256]))

In [17]:
x.reshape(-1).shape, y.reshape(-1).shape

(torch.Size([65536]), torch.Size([65536]))

In [18]:
B = 4
grid_ray_o = torch.stack([x.reshape(-1), y.reshape(-1), torch.ones(HL*HL)], dim=-1).expand(B, -1, -1)
grid_ray_o.shape

torch.Size([4, 65536, 3])

In [19]:
import torch

# 示例张量
t = torch.tensor([[1, 2], [3, 4], [5, 6]])

# 索引张量
index = torch.tensor([[0, 1], [1, 0], [0, 0]])

# 沿着列（dim=1）根据索引选择数据
result = torch.gather(t, 1, index)

print(result)


tensor([[1, 2],
        [4, 3],
        [5, 5]])


In [25]:
sigma = 1
rgb = 3
print("shape:", sigma, ", shape:", rgb)

shape: 1 , shape: 3


In [2]:
import numpy as np

data = np.load("GRAM-HD/bmvs_data/bmvs_bear/cameras_sphere.npz")
data.files

['scale_mat_0',
 'world_mat_0',
 'scale_mat_1',
 'world_mat_1',
 'scale_mat_2',
 'world_mat_2',
 'scale_mat_3',
 'world_mat_3',
 'scale_mat_4',
 'world_mat_4',
 'scale_mat_5',
 'world_mat_5',
 'scale_mat_6',
 'world_mat_6',
 'scale_mat_7',
 'world_mat_7',
 'scale_mat_8',
 'world_mat_8',
 'scale_mat_9',
 'world_mat_9',
 'scale_mat_10',
 'world_mat_10',
 'scale_mat_11',
 'world_mat_11',
 'scale_mat_12',
 'world_mat_12',
 'scale_mat_13',
 'world_mat_13',
 'scale_mat_14',
 'world_mat_14',
 'scale_mat_15',
 'world_mat_15',
 'scale_mat_16',
 'world_mat_16',
 'scale_mat_17',
 'world_mat_17',
 'scale_mat_18',
 'world_mat_18',
 'scale_mat_19',
 'world_mat_19',
 'scale_mat_20',
 'world_mat_20',
 'scale_mat_21',
 'world_mat_21',
 'scale_mat_22',
 'world_mat_22',
 'scale_mat_23',
 'world_mat_23',
 'scale_mat_24',
 'world_mat_24',
 'scale_mat_25',
 'world_mat_25',
 'scale_mat_26',
 'world_mat_26',
 'scale_mat_27',
 'world_mat_27',
 'scale_mat_28',
 'world_mat_28',
 'scale_mat_29',
 'world_mat_29',


In [5]:
scal = data['scale_mat_0']
scal

array([[ 1.6737139,  0.       ,  0.       , -2.702419 ],
       [ 0.       ,  1.6737139,  0.       , -1.3968586],
       [ 0.       ,  0.       ,  1.6737139, 27.347609 ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)

In [7]:
world = data['world_mat_0']
world

array([[-1.0889766e+02,  3.2340955e+02,  6.2724188e+02, -1.6156446e+04],
       [-4.8021997e+02, -3.6971255e+02,  2.8318774e+02, -8.9503633e+03],
       [ 2.4123600e-01, -4.2752099e-01,  8.7122399e-01, -2.1731400e+01],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]],
      dtype=float32)

In [8]:
data['scale_mat_1']

array([[ 1.6737139,  0.       ,  0.       , -2.702419 ],
       [ 0.       ,  1.6737139,  0.       , -1.3968586],
       [ 0.       ,  0.       ,  1.6737139, 27.347609 ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)

In [9]:
data['world_mat_1']

array([[ 6.0832639e+00,  2.4138771e+02,  6.7199725e+02, -1.7233209e+04],
       [-5.5755878e+02, -2.6004559e+02,  2.6267581e+02, -8.5326475e+03],
       [ 1.3378300e-01, -6.0538799e-01,  7.8460699e-01, -2.0310301e+01],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]],
      dtype=float32)

In [10]:
data['scale_mat_8']

array([[ 1.6737139,  0.       ,  0.       , -2.702419 ],
       [ 0.       ,  1.6737139,  0.       , -1.3968586],
       [ 0.       ,  0.       ,  1.6737139, 27.347609 ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)

In [11]:
data['scale_mat_122']

array([[ 1.6737139,  0.       ,  0.       , -2.702419 ],
       [ 0.       ,  1.6737139,  0.       , -1.3968586],
       [ 0.       ,  0.       ,  1.6737139, 27.347609 ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)